2022-02-01 00:02:13,917 (util.py:66 WorkerThread2) ERROR - TeleBot: "TypeError occurred, args=('%d format: a number is required, not unicode',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "bot.py", line 92, in pidor_message
    result = dblogic.PushScore(dblogic.ConnectDB("db_Pidor"), message.chat.id, spisok[pidor][2])
  File "/home/mberezovskiy/project/DB/dblogic.py", line 94, in PushScore
    mycursor.execute(sql % value)
TypeError: %d format: a number is required, not unicode
"
2022-02-01 00:02:19,174 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:02:29,175 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:02:34,179 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:02:39,200 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:02:44,192 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:02:49,208 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:02:54,210 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:02:59,203 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:03:04,208 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:03:09,232 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:03:14,211 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:03:19,217 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:03:24,211 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:03:29,219 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:03:34,221 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:03:39,230 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:03:44,234 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:03:49,240 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:03:54,244 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:03:59,253 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:04:04,256 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:04:09,279 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:04:14,266 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:04:19,272 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:04:24,281 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:04:29,279 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:04:34,289 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:04:39,306 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:04:44,315 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:04:49,322 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:04:54,327 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:04:59,318 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:05:04,326 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:05:09,346 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:05:14,336 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:05:19,351 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:05:24,341 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:05:29,355 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:05:34,360 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:05:39,347 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:05:44,355 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:05:49,366 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:05:54,365 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:05:59,359 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:06:04,363 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:06:09,362 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:06:14,374 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:06:19,374 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:06:24,382 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:06:29,385 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:06:34,389 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:06:39,398 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:06:44,411 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:06:58,242 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 502 Bad Gateway. Response body:\n[{"ok":false,"error_code":502,"description":"Bad Gateway"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 502 Bad Gateway. Response body:
[{"ok":false,"error_code":502,"description":"Bad Gateway"}]
"
2022-02-01 00:06:58,255 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 502 Bad Gateway. Response body:\n[{"ok":false,"error_code":502,"description":"Bad Gateway"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 502 Bad Gateway. Response body:
[{"ok":false,"error_code":502,"description":"Bad Gateway"}]
"
2022-02-01 00:06:59,418 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 502 Bad Gateway. Response body:\n[{"ok":false,"error_code":502,"description":"Bad Gateway"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 502 Bad Gateway. Response body:
[{"ok":false,"error_code":502,"description":"Bad Gateway"}]
"
2022-02-01 00:07:18,771 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:07:21,774 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:07:23,652 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:07:29,466 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:07:34,391 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:07:39,474 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:07:44,477 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:07:49,489 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:07:54,531 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:07:59,515 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:08:04,504 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:08:14,519 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:08:19,523 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:08:24,523 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:08:29,521 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:08:34,548 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:08:39,541 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:08:44,555 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:08:49,559 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:08:54,568 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:08:59,586 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:09:09,599 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:09:14,638 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:09:19,606 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:09:24,617 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:09:29,635 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:09:34,635 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:09:39,628 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:09:44,647 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:09:49,657 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:09:54,642 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:09:59,655 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:10:04,663 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:10:09,642 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:10:14,681 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:10:19,665 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:10:24,664 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:10:29,669 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:10:34,679 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:10:39,675 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:10:44,678 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:10:49,691 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:10:54,690 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:10:59,693 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:11:04,699 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:11:09,723 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:11:14,707 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:11:19,719 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:11:24,721 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:11:29,726 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:11:34,738 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:11:39,731 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
2022-02-01 00:11:44,737 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]',)
Traceback (most recent call last):
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/mberezovskiy/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}]
"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      